import type { NextPage } from 'next'
import Head from 'next/head'
import 'antd/dist/antd.css';
import AuthLayout from "../layout/AuthLayout/AuthLayout";
import React from 'react';
import Login from "../components/Login/Login";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <AuthLayout>
            <Login />
        </AuthLayout>
    </div>
  )
}

export default Home
