fragment Dialog on DialogsEntity {
    id
    info {
        id
        name
        image {
            id
            filePath
        }
    }
    messages {
        id
        text
        owner {
            id
            profile {
                id
                avatar {
                    id
                    filePath
                }
                firstName
            }
        }
        createdAt
    }
}
