fragment Users on UserEntity {
    id
    profile {
        id
        avatar {
            id
            filePath
        }
        firstName
        lastName
        middleName
    }
    login
    email
}
