mutation UpdateProfile(
    $about: String
    $birthday: String
    $city: String
    $country: String
    $createdAt: DateTime!
    $email: String!
    $firstName: String!
    $lastName: String!
    $login: String!
    $middleName: String!
    $phone: String!
    $relatives: String
    $school: String
    $status: String
    $updatedAt: DateTime!
) {
    edit(data: {
        about: $about
        city: $city
        birthday: $birthday
        country: $country
        createdAt: $createdAt
        email: $email
        firstName: $firstName
        lastName: $lastName
        login: $login
        middleName: $middleName
        phone: $phone
        relatives: $relatives
        school: $school
        status: $status
        updatedAt: $updatedAt
    }) {
        ...PersonFragment
    }
}
